apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-kaat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-kaat
    app.kubernetes.io/part-of: tkrw-pr712-0075-0060-app
  name: devfile-sample-kaat
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-kaat
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-kaat
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0060-tenant/tkrw-pr712-0075-0060-app/devfile-sample-kaat@sha256:71cb278ab15f122d51c4f4e8bb0b9b5b4cad5d93b247e4eba524a0a35e384097
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
